# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170116_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
    ]
