# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 04:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 15, 4, 26, 49, 126430, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 15, 4, 27, 5, 752421, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
