# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170215_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='TimeStamp',
            new_name='created',
        ),
    ]
