# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default=datetime.datetime(2017, 2, 16, 10, 27, 4, 477237, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
