# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
